AllCops:
  TargetRubyVersion: 2.5.0
  Exclude:
    - 'Rakefile'
    - 'config.ru'
    - 'Gemfile'
    - 'bin/*'
    - 'config/**/*.rb'
    - 'db/**/*.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/support/factory_girl.rb'
BlockLength:
    Max: 200
Metrics/LineLength:
    Max: 80
    IgnoredPatterns: ['\A#']
Metrics/AbcSize:
    Enabled: false
